version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loja
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/mysql
      - ./database/produtos.sql:/docker-entrypoint-initdb.d/0_init.sql
volumes:
  db-data: